/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'gamePackage' : string,
  'date' : Time,
  'name' : string,
  'message' : [] | [string],
  'phone' : string,
  'groupSize' : bigint,
}
export interface Score {
  'date' : Time,
  'game' : string,
  'score' : bigint,
  'playerName' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addBooking' : ActorMethod<
    [string, string, Time, string, bigint, [] | [string]],
    undefined
  >,
  'getBookings' : ActorMethod<[], Array<Booking>>,
  'getGlobalLeaderboard' : ActorMethod<[], Array<Score>>,
  'getLeaderboard' : ActorMethod<[string], Array<Score>>,
  'submitScore' : ActorMethod<[string, string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];