/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const BookingInput = IDL.Record({
  'gamePackage' : IDL.Text,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'message' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'screenshot' : IDL.Opt(ExternalBlob),
  'groupSize' : IDL.Nat,
});
export const Booking = IDL.Record({
  'bookingId' : IDL.Text,
  'gamePackage' : IDL.Text,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'message' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'screenshot' : IDL.Opt(ExternalBlob),
  'groupSize' : IDL.Nat,
});
export const Time = IDL.Int;
export const Score = IDL.Record({
  'date' : Time,
  'game' : IDL.Text,
  'score' : IDL.Nat,
  'playerName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addBooking' : IDL.Func([BookingInput], [IDL.Text], []),
  'deleteBooking' : IDL.Func([IDL.Text], [], []),
  'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getGlobalLeaderboard' : IDL.Func([], [IDL.Vec(Score)], ['query']),
  'getLeaderboard' : IDL.Func([IDL.Text], [IDL.Vec(Score)], ['query']),
  'submitScore' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const BookingInput = IDL.Record({
    'gamePackage' : IDL.Text,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'message' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'screenshot' : IDL.Opt(ExternalBlob),
    'groupSize' : IDL.Nat,
  });
  const Booking = IDL.Record({
    'bookingId' : IDL.Text,
    'gamePackage' : IDL.Text,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'message' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'screenshot' : IDL.Opt(ExternalBlob),
    'groupSize' : IDL.Nat,
  });
  const Time = IDL.Int;
  const Score = IDL.Record({
    'date' : Time,
    'game' : IDL.Text,
    'score' : IDL.Nat,
    'playerName' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addBooking' : IDL.Func([BookingInput], [IDL.Text], []),
    'deleteBooking' : IDL.Func([IDL.Text], [], []),
    'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getGlobalLeaderboard' : IDL.Func([], [IDL.Vec(Score)], ['query']),
    'getLeaderboard' : IDL.Func([IDL.Text], [IDL.Vec(Score)], ['query']),
    'submitScore' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };