/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'bookingId' : string,
  'gamePackage' : string,
  'date' : string,
  'name' : string,
  'message' : [] | [string],
  'phone' : string,
  'screenshot' : [] | [ExternalBlob],
  'groupSize' : bigint,
}
export interface BookingInput {
  'gamePackage' : string,
  'date' : string,
  'name' : string,
  'message' : [] | [string],
  'phone' : string,
  'screenshot' : [] | [ExternalBlob],
  'groupSize' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Score {
  'date' : Time,
  'game' : string,
  'score' : bigint,
  'playerName' : string,
}
export type Time = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addBooking' : ActorMethod<[BookingInput], string>,
  'deleteBooking' : ActorMethod<[string], undefined>,
  'getBookings' : ActorMethod<[], Array<Booking>>,
  'getGlobalLeaderboard' : ActorMethod<[], Array<Score>>,
  'getLeaderboard' : ActorMethod<[string], Array<Score>>,
  'submitScore' : ActorMethod<[string, string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];